# Generated by Django 4.2.4 on 2023-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0004_businesspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeStylePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='LifeStyle/images')),
                ('inline_category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(verbose_name='Yangilik matni')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Business/images')),
                ('inline_category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(verbose_name='Yangilik matni')),
            ],
        ),
    ]
