# Generated by Django 4.2.4 on 2023-08-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0005_lifestylepost_travelpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNewsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('news_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_news.newstitle')),
            ],
        ),
    ]
