# Generated by Django 4.2.4 on 2023-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0007_newstitle_powered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstitle',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
