# Generated by Django 4.2.4 on 2023-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0008_newstitle_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstitle',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='social_google',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
