# Generated by Django 4.2.4 on 2023-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0009_newstitle_social_facebook_newstitle_social_google_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstitle',
            name='inline_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
