# Generated by Django 4.2.4 on 2023-08-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0011_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopularPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('news_post', models.CharField(max_length=155, verbose_name='Yangi post')),
            ],
        ),
    ]
