# Generated by Django 4.2.4 on 2023-08-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0012_mostpopularpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MostPopularPost',
        ),
    ]
