# Generated by Django 4.2.4 on 2023-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0014_mostpopularpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostpopularpost',
            name='urls',
            field=models.CharField(max_length=375, verbose_name='Havola'),
        ),
    ]
