# Generated by Django 4.2.4 on 2023-08-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0016_featuredvideopost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedVideoPost',
        ),
    ]
