# Generated by Django 4.2.4 on 2023-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0017_delete_featuredvideopost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedVideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.CharField(auto_created='https://www.youtube.com/watch?v=ZCtmmjD0Avs', max_length=255)),
                ('title', models.CharField(default='Clearing form video', max_length=255, serialize=1234)),
                ('author', models.CharField(default='Shavkat Xusenaliyev', max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
