# Generated by Django 4.2.4 on 2023-08-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0019_tagspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestArticlesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('photo', models.ImageField(upload_to='LatestArticles/images')),
                ('title', models.CharField(default='Let me know if you have any further questions!', max_length=255, serialize=99)),
                ('author', models.CharField(default='Shavkat Xusenaliyev', max_length=22)),
            ],
        ),
    ]
