services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .

    depends_on:
      - db

    ports:
      - "8000:8000"
    volumes:
      - .:/code